language: node_js
node_js:
   - "0.12.4"

branches:
  only:
    - master

script:
  npm test

after_success:
  - 'cat ./coverage/report-lcov/lcov.info | ./node_modules/.bin/coveralls.js'
  - 'cat ./coverage/report-lcov/lcov.info' #just want to see if this contains anything

sudo: false

before_install:
  npm install

notifications:
  email: false

addons:
  sauce_connect:true